# Generated by Django 5.0.3 on 2024-04-05 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0005_alter_items_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(default=1000000, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('bussiness_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales_WebApp.bussiness')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
