# Generated by Django 5.0.3 on 2024-04-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0006_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(default=1000005, primary_key=True, serialize=False),
        ),
    ]
