# Generated by Django 5.0.3 on 2024-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0008_alter_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_total',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
