# Generated by Django 5.0.3 on 2024-04-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0010_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='total_cost',
        ),
    ]
