# Generated by Django 5.0.3 on 2024-04-22 23:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0012_inventory_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventory_item',
            new_name='inventory_location',
        ),
    ]
