# Generated by Django 5.0.3 on 2024-04-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0013_rename_inventory_item_inventory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='location_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales_WebApp.inventory_location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='location_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales_WebApp.inventory_location'),
            preserve_default=False,
        ),
    ]
