# Generated by Django 5.0.3 on 2024-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0014_purchase_location_name_sale_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='location_address',
            field=models.CharField(default='unspecified location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='location_address',
            field=models.CharField(default='unspecified location', max_length=100),
            preserve_default=False,
        ),
    ]
