# Generated by Django 5.0.3 on 2024-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0015_purchase_location_address_sale_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_location',
            name='total_item',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
