# Generated by Django 5.0.3 on 2024-04-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0016_inventory_location_total_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='location_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales_WebApp.inventory_location'),
            preserve_default=False,
        ),
    ]
