# Generated by Django 5.0.3 on 2024-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales_WebApp', '0017_items_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='location_address',
            field=models.CharField(default='unspecified location', max_length=100),
            preserve_default=False,
        ),
    ]
